export const researchData = [
    {
      tag: "Tag 2",
      uni: "Uni 2",
      title: "K ",
      progress: "D",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 1",
      uni: "Uni 1",
      title: "D ",
      progress: "P",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 5",
      uni: "Uni 5",
      title: "J",
      progress: "C",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 9",
      uni: "Uni 9",
      title: "A",
      progress: "C",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 3",
      uni: "Uni 3",
      title: "M",
      progress: "P",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 7",
      uni: "Uni 7",
      title: "S",
      progress: "C",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 7",
      uni: "Uni 7",
      title: "S",
      progress: "C",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 7",
      uni: "Uni 7",
      title: "S",
      progress: "C",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 7",
      uni: "Uni 7",
      title: "S",
      progress: "C",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
    {
      tag: "Tag 7",
      uni: "Uni 7",
      title: "S",
      progress: "C",
      link: "Link ",
      dateAdded: "xx/yy/zzzz",
    },
  ];